name: Build and test
on: push

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Upload GH pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - run: npm install
      - run: npm run test
